//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFLicensesDialog {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFLicensesDialog.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///                                 Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///      the copyright owner that  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string asl_20_full {
            get {
                return ResourceManager.GetString("asl_20_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at
        ///
        ///    http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations u [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string asl_20_summary {
            get {
                return ResourceManager.GetString("asl_20_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
        ///THIS SOFTWARE IS PROVIDED BY THE COP [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bsd2_full {
            get {
                return ResourceManager.GetString("bsd2_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 的本地化字符串。
        /// </summary>
        internal static string bsd2_summary {
            get {
                return ResourceManager.GetString("bsd2_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
        ///Neither the name of the &lt;ORGANIZATIO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bsd3_full {
            get {
                return ResourceManager.GetString("bsd3_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
        ///Neither the name of the &lt;ORGANIZATIO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bsd3_summary {
            get {
                return ResourceManager.GetString("bsd3_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creative Commons Legal Code
        ///
        ///Attribution-NoDerivs 3.0 Unported
        ///
        ///    CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE
        ///    LEGAL SERVICES. DISTRIBUTION OF THIS LICENSE DOES NOT CREATE AN
        ///    ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS
        ///    INFORMATION ON AN &quot;AS-IS&quot; BASIS. CREATIVE COMMONS MAKES NO WARRANTIES
        ///    REGARDING THE INFORMATION PROVIDED, AND DISCLAIMS LIABILITY FOR
        ///    DAMAGES RESULTING FROM ITS USE.
        ///
        ///License
        ///
        ///THE WORK (AS DEFINED BELOW) IS PROVIDED UN [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ccand_30_full {
            get {
                return ResourceManager.GetString("ccand_30_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are free to:
        ///
        ///    Share - copy and redistribute the material in any medium or format for any purpose, even commercially.
        ///    The licensor cannot revoke these freedoms as long as you follow the license terms.
        ///
        ///Under the following terms:
        ///
        ///    Attribution - You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
        ///    NoDerivatives - If you remix, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ccand_30_summary {
            get {
                return ResourceManager.GetString("ccand_30_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creative Commons Legal Code
        ///
        ///Attribution 3.0 Unported
        ///
        ///    CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE
        ///    LEGAL SERVICES. DISTRIBUTION OF THIS LICENSE DOES NOT CREATE AN
        ///    ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS
        ///    INFORMATION ON AN &quot;AS-IS&quot; BASIS. CREATIVE COMMONS MAKES NO WARRANTIES
        ///    REGARDING THE INFORMATION PROVIDED, AND DISCLAIMS LIABILITY FOR
        ///    DAMAGES RESULTING FROM ITS USE.
        ///
        ///License
        ///
        ///THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE T [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ccby_30_full {
            get {
                return ResourceManager.GetString("ccby_30_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are free to:
        ///
        ///    Share — copy and redistribute the material in any medium or format
        ///    Adapt — remix, transform, and build upon the material for any purpose, even commercially.
        ///    The licensor cannot revoke these freedoms as long as you follow the license terms.
        ///
        ///Under the following terms:
        ///
        ///    Attribution - You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor e [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ccby_30_summary {
            get {
                return ResourceManager.GetString("ccby_30_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creative Commons Legal Code
        ///
        ///Attribution-ShareAlike 3.0 Unported
        ///
        ///    CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE
        ///    LEGAL SERVICES. DISTRIBUTION OF THIS LICENSE DOES NOT CREATE AN
        ///    ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS
        ///    INFORMATION ON AN &quot;AS-IS&quot; BASIS. CREATIVE COMMONS MAKES NO WARRANTIES
        ///    REGARDING THE INFORMATION PROVIDED, AND DISCLAIMS LIABILITY FOR
        ///    DAMAGES RESULTING FROM ITS USE.
        ///
        ///License
        ///
        ///THE WORK (AS DEFINED BELOW) IS PROVIDED  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ccbysa_30_full {
            get {
                return ResourceManager.GetString("ccbysa_30_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are free to:
        ///
        ///    Share — copy and redistribute the material in any medium or format
        ///    Adapt — remix, transform, and build upon the material for any purpose, even commercially.
        ///    The licensor cannot revoke these freedoms as long as you follow the license terms.
        ///
        ///Under the following terms:
        ///
        ///    Attribution - You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor e [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ccbysa_30_summary {
            get {
                return ResourceManager.GetString("ccbysa_30_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eclipse Public License - v 1.0
        ///
        ///THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE PUBLIC LICENSE (&quot;AGREEMENT&quot;). ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM CONSTITUTES RECIPIENT&apos;S ACCEPTANCE OF THIS AGREEMENT.
        ///
        ///1. DEFINITIONS
        ///
        ///&quot;Contribution&quot; means:
        ///
        ///a) in the case of the initial Contributor, the initial code and documentation distributed under this Agreement, and
        ///b) in the case of each subsequent Contributor:
        ///i) changes to the Program, and
        ///ii) additions to the Program; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string epl_v10_full {
            get {
                return ResourceManager.GetString("epl_v10_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This license, made and used by the Eclipse Foundation, is similar to GPL but allows you to link code under the license to proprietary applications. You may also license binaries under a proprietary license, as long as the source code is available under EPL. 的本地化字符串。
        /// </summary>
        internal static string epl_v10_summary {
            get {
                return ResourceManager.GetString("epl_v10_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h3&gt;&lt;a id=&quot;SEC1&quot;&gt;GNU GENERAL PUBLIC LICENSE&lt;/a&gt;&lt;/h3&gt;
        ///&lt;p&gt;
        ///Version 2, June 1991
        ///&lt;/p&gt;
        ///
        ///&lt;pre&gt;
        ///Copyright (C) 1989, 1991 Free Software Foundation, Inc.  
        ///51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
        ///
        ///Everyone is permitted to copy and distribute verbatim copies
        ///of this license document, but changing it is not allowed.
        ///&lt;/pre&gt;
        ///
        ///&lt;h3&gt;&lt;a id=&quot;preamble&quot;&gt;&lt;/a&gt;&lt;a id=&quot;SEC2&quot;&gt;Preamble&lt;/a&gt;&lt;/h3&gt;
        ///
        ///&lt;p&gt;
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string gpl_20_full {
            get {
                return ResourceManager.GetString("gpl_20_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU General Public License
        ///as published by the Free Software Foundation; either version 2
        ///of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///GNU General Public License for more details.
        ///
        ///You should have received a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string gpl_20_summary {
            get {
                return ResourceManager.GetString("gpl_20_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h3 style=&quot;text-align: center;&quot;&gt;GNU GENERAL PUBLIC LICENSE&lt;/h3&gt;
        ///&lt;p style=&quot;text-align: center;&quot;&gt;Version 3, 29 June 2007&lt;/p&gt;
        ///
        ///&lt;p&gt;Copyright &amp;copy; 2007 Free Software Foundation, Inc.
        /// &amp;lt;&lt;a href=&quot;http://fsf.org/&quot;&gt;http://fsf.org/&lt;/a&gt;&amp;gt;&lt;/p&gt;&lt;p&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.&lt;/p&gt;
        ///
        ///&lt;h3&gt;&lt;a name=&quot;preamble&quot;&gt;&lt;/a&gt;Preamble&lt;/h3&gt;
        ///
        ///&lt;p&gt;The GNU General Public License is a free, copyleft license for
        ///software and other kinds  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string gpl_30_full {
            get {
                return ResourceManager.GetString("gpl_30_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program is free software: you can redistribute it and/or modify
        ///it under the terms of the GNU General Public License as published by
        ///the Free Software Foundation, either version 3 of the License, or
        ///(at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///GNU General Public License for more details.
        ///
        ///You should have received a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string gpl_30_summary {
            get {
                return ResourceManager.GetString("gpl_30_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission to use, copy, modify, and/or distribute this software for
        ///any purpose with or without fee is hereby granted, provided that this
        ///permission notice appear in all copies.
        ///
        ///THE SOFTWARE IS PROVIDED &quot;AS IS&quot; AND THE AUTHOR DISCLAIMS ALL WARRANTIES
        ///WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
        ///AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
        ///INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
        ///LOSS OF USE, DATA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string isc_full {
            get {
                return ResourceManager.GetString("isc_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that this permission notice appear in all copies.
        ///
        ///THE SOFTWARE IS PROVIDED &quot;AS IS&quot; AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY  AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR P [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string isc_summary {
            get {
                return ResourceManager.GetString("isc_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似                   GNU LESSER GENERAL PUBLIC LICENSE
        ///                       Version 2.1, February 1999
        ///
        /// Copyright (C) 1991, 1999 Free Software Foundation, Inc.
        /// 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///[This is the first released version of the Lesser GPL.  It also counts
        /// as the successor of the GNU Library Public License, version 2, hence
        /// the version numb [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lgpl_21_full {
            get {
                return ResourceManager.GetString("lgpl_21_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
        ///
        ///This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
        ///
        ///You should have r [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lgpl_21_summary {
            get {
                return ResourceManager.GetString("lgpl_21_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似                    GNU LESSER GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///
        ///  This version of the GNU Lesser General Public License incorporates
        ///the terms and conditions of version 3 of the GNU General Public
        ///License, supplemented by the additional permissions listed below.
        ///
        ///  0. Ad [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lgpl_3_full {
            get {
                return ResourceManager.GetString("lgpl_3_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
        ///
        ///This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
        ///
        ///You should have rec [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lgpl_3_summary {
            get {
                return ResourceManager.GetString("lgpl_3_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included in a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mit_full {
            get {
                return ResourceManager.GetString("mit_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included in a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mit_summary {
            get {
                return ResourceManager.GetString("mit_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似                      MOZILLA PUBLIC LICENSE
        ///                           Version 1.1
        ///
        ///                         ---------------
        ///
        ///1. Definitions.
        ///
        ///1.0.1. &quot;Commercial Use&quot; means distribution or otherwise making the
        ///Covered Code available to a third party.
        ///
        ///1.1. &quot;Contributor&quot; means each entity that creates or contributes to
        ///the creation of Modifications.
        ///
        ///1.2. &quot;Contributor Version&quot; means the combination of the Original
        ///Code, prior Modifications used by a Contributor, and the Modifications
        ///made by t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mpl_11_full {
            get {
                return ResourceManager.GetString("mpl_11_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Source Code Form is subject to the terms of the Mozilla Public
        ///License, v. 1.1. If a copy of the MPL was not distributed with this
        ///file, You can obtain one at http://mozilla.org/MPL/1.1/. 的本地化字符串。
        /// </summary>
        internal static string mpl_11_summary {
            get {
                return ResourceManager.GetString("mpl_11_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mozilla Public License Version 2.0
        ///==================================
        ///
        ///1. Definitions
        ///--------------
        ///
        ///1.1. &quot;Contributor&quot;
        ///    means each individual or legal entity that creates, contributes to
        ///    the creation of, or owns Covered Software.
        ///
        ///1.2. &quot;Contributor Version&quot;
        ///    means the combination of the Contributions of others (if any) used
        ///    by a Contributor and that particular Contributor&apos;s Contribution.
        ///
        ///1.3. &quot;Contribution&quot;
        ///    means Covered Software of a particular Contributor.
        ///
        ///1.4. &quot;Cove [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mpl_20_full {
            get {
                return ResourceManager.GetString("mpl_20_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Source Code Form is subject to the terms of the Mozilla Public
        ///License, v. 2.0. If a copy of the MPL was not distributed with this
        ///file, You can obtain one at http://mozilla.org/MPL/2.0/. 的本地化字符串。
        /// </summary>
        internal static string mpl_20_summary {
            get {
                return ResourceManager.GetString("mpl_20_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SIL OPEN FONT LICENSE
        ///
        ///Version 1.1 - 26 February 2007
        ///
        ///PREAMBLE The goals of the Open Font License (OFL) are to stimulate worldwide development of collaborative font projects, to support the font creation efforts of academic and linguistic communities, and to provide a free and open framework in which fonts may be shared and improved in partnership with others.
        ///
        ///The OFL allows the licensed fonts to be used, studied, modified and redistributed freely as long as they are not sold by themselves. The font [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sil_ofl_11_full {
            get {
                return ResourceManager.GetString("sil_ofl_11_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFL is used by almost all libre fonts. Selling fonts by themselves is not allowed, but bundling with software or selling font design services is allowed. Font names must usually be changed before making any modifications. Document embedding is allowed. 的本地化字符串。
        /// </summary>
        internal static string sil_ofl_11_summary {
            get {
                return ResourceManager.GetString("sil_ofl_11_summary", resourceCulture);
            }
        }
    }
}
